services:
  mysql:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: passwd
    ports:
      - 3306:3306
    volumes:
      - /home/peter/egyetem/adatbazisok/:/var/db/

  hod:
    image: dbeaver/cloudbeaver
    ports:
      - 8080:8978
    volumes:
      - /home/peter/egyetem/adatbazisok/:/opt/cloudbeaver/workspace
